### ISSUE TITLE
Zoho Subscription removed AuthToken from Support 

### ISSUE THREAD

**Issue by lonormaly** [sudiptochoudhury/php-zoho-subscriptions#2]
Zoho Subscription removed AuthToken from Support. They now use OAuth2... Will that be supported as well?

**Comment by sudiptochoudhury** [comment]
Not yet, but will check and update.

**Comment by sudiptochoudhury** [comment]
The support for OAuth token has been added in `master` branch. Will be released soon. 
The change is not much. All you will need is to instead of passing `authtoken` property, pass your oauthtoken via `oauthtoken` property of the constructor parameter. Make sure not to pass `authtoken` anymore if your are passing `oauthtoken`.

**Comment by lonormaly** [comment]
Did you notice the api is v2? and not v1?

**Comment by sudiptochoudhury** [comment]
No. In fact I still see it as v1 from https://www.zoho.com/in/subscriptions/developer-api/ which leads to https://www.zoho.com/subscriptions/api/v1/

Let's be clear here. My reference here is to `Zoho Subscription API` and not `OAuth 2 API` or any other `Zoho` services. This library, so far, does not involve in creating/generating/revoking any of the tokens (OAuth or auth).

**Comment by lonormaly** [comment]
Thanks a lot! also, how do you generate an access_token from the refresh_token using your package? Or should I handle expiration of access_token by myself? Because as for now the access_token (oauth) expires every 60 minutes

**Comment by sudiptochoudhury** [comment]
As of now, yes, you need to handle it yourself. However, I will soon add a separate class to manage OAuth2 related items.
